export const footerLinks = [
    {
        title: "A propos",
        links: [
            { title: "Comment ca marche", url: "/" },
            { title: "Associé", url: "/" },
            { title: "Partenaria", url: "/" },
            { title: "Bussiness Relation", url: "/" },
        ],
    },
    {
        title: "Société",
        links: [
            { title: "Evenement", url: "/event" },
            { title: "Blog", url: "/" },
            { title: "Podcast", url: "/" },
            { title: "Invite un ami", url: "/" },
        ],
    },
    {
        title: "Réseaux sociaux",
        links: [
            { title: "Lifeinvader", url: "/" },
            { title: "Birdy", url: "/" },
            { title: "InstaPic", url: "/" },
            { title: "Trendy", url: "/" },
        ],
    },
];

export const Manufacturer = [
    "Toutes",
    "Autres",
    "Albany",
    "Annis",
    "Benefactor",
    "BF",
    "Bollokan",
    "Bravado",
    "Brute",
    "Buckingham",
    "Canis",
    "Chariot",
    "Cheval",
    "Coil",
    "Declasse",
    "Dewbauchee",
    "Dinka",
    "Dundreary",
    "Emperor",
    "Enus",
    "Fathom",
    "Gallivanter",
    "Grotti",
    "Hijak",
    "HVY",
    "Imponte",
    "Invetero",
    "Jacksheepe",
    "Jobuilt",
    "Karin",
    "Kraken",
    "Lampadati",
    "LCC",
    "Maibatsu",
    "Mammoth",
    "Maxwell",
    "MTL",
    "Nagasaki",
    "Obey",
    "Ocelot",
    "Overflod",
    "Pegassi",
    "Pfister",
    "Principe",
    "Progen",
    "Rune",
    "Schyster",
    "Shitzu",
    "Speedophile",
    "Stanley",
    "Truffade",
    "Ubermacht",
    "Vapid",
    "Vulcar",
    "Vysser",
    "Weeny",
    "Western",
    "Willard",
    "Zirconium",
    "Bordeau",
];

export const Categories = [
    "Sport Classic",
    "Compact",
    "Coupe",
    "Moto",
    "Muscles",
    "Tout Terrain",
    "SUV",
    "Sedans",
    "Sport",
    "Super",
    "Van",
    "Bateaux",
    "Aériens",
]